import React, { useState, useRef, useEffect, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { base44 } from "@/api/base44Client";
import { toast } from "sonner";
import {
  Code2, Terminal, GitBranch, Play, Square, Plus, X, Copy, Download, Upload,
  Cpu, Zap, ChevronRight, ChevronDown, Folder, FolderOpen, FileCode, Package,
  RefreshCw, Check, AlertCircle, Loader2, Settings, Database, Cloud, Lock,
  ArrowRight, Activity, Network, Bot, Layers, LayoutGrid, Save, Search, Bug
} from "lucide-react";

// ── Language definitions ──────────────────────────────────────────────────────
const LANG_MAP = {
  js: "javascript", jsx: "javascript", ts: "typescript", tsx: "typescript",
  py: "python", sh: "bash", yml: "yaml", yaml: "yaml", json: "json",
  sql: "sql", dockerfile: "dockerfile", md: "markdown", css: "css", html: "html",
};

const LANG_COLORS = {
  javascript: "#f7df1e", typescript: "#3178c6", python: "#3776ab",
  bash: "#4eaa25", yaml: "#cb171e", json: "#5da5d5", sql: "#e38c00",
  dockerfile: "#0db7ed", markdown: "#083fa1", css: "#1572b6", html: "#e34f26",
};

// ── Default starter files ─────────────────────────────────────────────────────
const DEFAULT_FILES = [
  {
    id: "main", name: "main.py", lang: "python",
    content: `# NexusVectis AI Orchestrator
# Generated by FLEET AI IDE

import asyncio
import json
from dataclasses import dataclass
from typing import List, Optional

@dataclass
class OrchestrationTask:
    id: str
    name: str
    priority: int
    dependencies: List[str]
    status: str = "pending"

async def orchestrate_fleet_ops(tasks: List[OrchestrationTask]):
    """AI-powered fleet orchestration engine."""
    print(f"[ORCHESTRATOR] Starting {len(tasks)} tasks...")
    
    completed = set()
    for task in sorted(tasks, key=lambda t: t.priority):
        deps_met = all(d in completed for d in task.dependencies)
        if deps_met:
            print(f"  ✓ Running: {task.name}")
            task.status = "running"
            await asyncio.sleep(0.1)  # Simulate work
            task.status = "completed"
            completed.add(task.id)
            print(f"  ✅ Done: {task.name}")
    
    return completed

if __name__ == "__main__":
    tasks = [
        OrchestrationTask("t1", "Load fleet telemetry", 1, []),
        OrchestrationTask("t2", "Run anomaly detection", 2, ["t1"]),
        OrchestrationTask("t3", "Optimize routes", 3, ["t1"]),
        OrchestrationTask("t4", "Generate report", 4, ["t2", "t3"]),
    ]
    asyncio.run(orchestrate_fleet_ops(tasks))
`
  },
  {
    id: "devops", name: "pipeline.yml", lang: "yaml",
    content: `# NexusVectis CI/CD Pipeline
name: Fleet AI Deployment

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE: nexusvectis/fleet-ai

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        run: |
          pip install pytest
          pytest tests/ -v --tb=short

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        run: |
          docker build -t \$IMAGE:\$GITHUB_SHA .
          docker push \$IMAGE:\$GITHUB_SHA

  deploy:
    needs: build
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/fleet-ai \\
            fleet-ai=\$IMAGE:\$GITHUB_SHA
          kubectl rollout status deployment/fleet-ai
`
  },
  {
    id: "api", name: "api.js", lang: "javascript",
    content: `// NexusVectis Fleet API — AI Orchestration Layer
// Powered by FLEET AI IDE

const express = require('express');
const app = express();
app.use(express.json());

// AI Orchestration middleware
const aiMiddleware = async (req, res, next) => {
  const start = Date.now();
  await next();
  const duration = Date.now() - start;
  console.log(\`[\${req.method}] \${req.path} — \${duration}ms\`);
};

// Fleet telemetry endpoint
app.get('/api/v1/fleet/telemetry', async (req, res) => {
  try {
    const { orgId, since } = req.query;
    
    // AI-powered anomaly detection
    const telemetry = await FleetAI.getTelemetry(orgId, since);
    const anomalies = await FleetAI.detectAnomalies(telemetry);
    
    res.json({
      status: 'ok',
      vehicles: telemetry.length,
      anomalies: anomalies.count,
      data: telemetry,
      ai_insights: anomalies.insights,
      timestamp: new Date().toISOString()
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// DevOps: Health check
app.get('/health', (req, res) => {
  res.json({
    status: 'healthy',
    uptime: process.uptime(),
    memory: process.memoryUsage(),
    version: process.env.APP_VERSION || '1.0.0'
  });
});

app.listen(3000, () => console.log('Fleet API running on :3000'));
`
  },
  {
    id: "dockerfile", name: "Dockerfile", lang: "dockerfile",
    content: `# NexusVectis Fleet AI — Production Dockerfile
FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production

COPY . .
RUN npm run build

# ── Production stage ──────────────────────────────────
FROM node:20-alpine AS runner

ENV NODE_ENV=production
WORKDIR /app

RUN addgroup --system --gid 1001 fleetai
RUN adduser --system --uid 1001 fleetai

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

USER fleetai
EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=10s --start-period=5s \\
  CMD wget --quiet --tries=1 --spider http://localhost:3000/health || exit 1

CMD ["node", "dist/server.js"]
`
  },
];

// ── Terminal Emulator ─────────────────────────────────────────────────────────
function TerminalEmulator({ output, isRunning, onClear }) {
  const endRef = useRef(null);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: "smooth" }); }, [output]);

  return (
    <div className="flex flex-col h-full bg-slate-950 font-mono text-xs">
      <div className="flex items-center justify-between px-3 py-1.5 border-b border-slate-800 bg-slate-900">
        <div className="flex items-center gap-2 text-slate-400">
          <Terminal className="w-3.5 h-3.5 text-green-400" />
          <span className="text-green-400 font-bold">TERMINAL</span>
          {isRunning && <span className="flex items-center gap-1 text-amber-400"><Loader2 className="w-3 h-3 animate-spin" />running</span>}
        </div>
        <button onClick={onClear} className="text-slate-600 hover:text-slate-400 text-[10px]">clear</button>
      </div>
      <div className="flex-1 overflow-auto p-3 space-y-0.5">
        {output.map((line, i) => (
          <div key={i} className={`leading-5 ${
            line.type === 'error' ? 'text-red-400' :
            line.type === 'success' ? 'text-green-400' :
            line.type === 'info' ? 'text-cyan-400' :
            line.type === 'warn' ? 'text-amber-400' :
            line.type === 'system' ? 'text-violet-400' :
            'text-slate-300'
          }`}>
            {line.type === 'system' && <span className="text-slate-600">$ </span>}
            {line.text}
          </div>
        ))}
        {isRunning && (
          <div className="text-green-400 animate-pulse">█</div>
        )}
        <div ref={endRef} />
      </div>
    </div>
  );
}

// ── Pipeline Visualizer ───────────────────────────────────────────────────────
const PIPELINE_STAGES = [
  { id: "code", label: "Code", icon: Code2, color: "#06b6d4" },
  { id: "test", label: "Test", icon: Check, color: "#10b981" },
  { id: "build", label: "Build", icon: Package, color: "#8b5cf6" },
  { id: "scan", label: "Security", icon: Lock, color: "#f59e0b" },
  { id: "deploy", label: "Deploy", icon: Cloud, color: "#3b82f6" },
  { id: "monitor", label: "Monitor", icon: Activity, color: "#ec4899" },
];

function PipelineVisualizer({ activeStage, stageStatus }) {
  return (
    <div className="p-4 bg-slate-900/80 border-b border-slate-800">
      <p className="text-[10px] text-slate-500 uppercase tracking-widest mb-3">CI/CD Pipeline</p>
      <div className="flex items-center gap-1">
        {PIPELINE_STAGES.map((stage, i) => {
          const Icon = stage.icon;
          const status = stageStatus[stage.id] || "idle";
          const isActive = activeStage === stage.id;
          return (
            <React.Fragment key={stage.id}>
              <div className={`flex flex-col items-center gap-1 px-2 py-1.5 rounded-lg transition-all ${
                isActive ? "bg-slate-700 ring-1" : "opacity-60"
              }`} style={isActive ? { ringColor: stage.color } : {}}>
                <div className={`w-7 h-7 rounded-full flex items-center justify-center ${
                  status === "success" ? "bg-green-500/20" :
                  status === "running" ? "bg-amber-500/20" :
                  status === "error" ? "bg-red-500/20" : "bg-slate-800"
                }`}>
                  {status === "running" ? (
                    <Loader2 className="w-3.5 h-3.5 animate-spin" style={{ color: stage.color }} />
                  ) : status === "success" ? (
                    <Check className="w-3.5 h-3.5 text-green-400" />
                  ) : status === "error" ? (
                    <AlertCircle className="w-3.5 h-3.5 text-red-400" />
                  ) : (
                    <Icon className="w-3.5 h-3.5 text-slate-500" />
                  )}
                </div>
                <span className="text-[9px] text-slate-400 font-mono">{stage.label}</span>
              </div>
              {i < PIPELINE_STAGES.length - 1 && (
                <ArrowRight className={`w-3 h-3 flex-shrink-0 ${
                  stageStatus[stage.id] === "success" ? "text-green-500" : "text-slate-700"
                }`} />
              )}
            </React.Fragment>
          );
        })}
      </div>
    </div>
  );
}

// ── File Explorer ─────────────────────────────────────────────────────────────
function FileExplorer({ files, activeFileId, onSelect, onNew, onDelete }) {
  const langDot = (lang) => {
    const color = LANG_COLORS[lang] || "#94a3b8";
    return <div className="w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: color }} />;
  };

  return (
    <div className="h-full bg-slate-950 border-r border-slate-800 flex flex-col" style={{ minWidth: 140, maxWidth: 160 }}>
      <div className="flex items-center justify-between px-2 py-1.5 border-b border-slate-800">
        <span className="text-[10px] text-slate-500 uppercase tracking-widest font-bold">Files</span>
        <button onClick={onNew} className="text-slate-500 hover:text-cyan-400 transition-colors">
          <Plus className="w-3.5 h-3.5" />
        </button>
      </div>
      <div className="flex-1 overflow-auto py-1">
        <div className="px-2 mb-1 flex items-center gap-1 text-slate-500">
          <FolderOpen className="w-3 h-3" />
          <span className="text-[10px]">nexusvectis</span>
        </div>
        {files.map(f => (
          <div key={f.id}
            className={`flex items-center gap-1.5 px-3 py-1 cursor-pointer group transition-colors ${
              f.id === activeFileId ? "bg-cyan-500/10 text-cyan-300" : "text-slate-400 hover:bg-slate-800 hover:text-slate-200"
            }`}
            onClick={() => onSelect(f.id)}
          >
            {langDot(f.lang)}
            <span className="text-[11px] flex-1 truncate font-mono">{f.name}</span>
            <button
              className="opacity-0 group-hover:opacity-100 text-slate-600 hover:text-red-400 transition-all ml-auto"
              onClick={(e) => { e.stopPropagation(); onDelete(f.id); }}
            >
              <X className="w-2.5 h-2.5" />
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}

// ── AI Command Panel ──────────────────────────────────────────────────────────
const AI_PRESETS = [
  { label: "Add error handling", icon: "🛡️" },
  { label: "Write unit tests", icon: "🧪" },
  { label: "Optimize performance", icon: "⚡" },
  { label: "Add TypeScript types", icon: "📦" },
  { label: "Create Dockerfile", icon: "🐳" },
  { label: "Generate REST API", icon: "🌐" },
  { label: "Add logging & metrics", icon: "📊" },
  { label: "Security audit", icon: "🔒" },
];

// ── Main Component ────────────────────────────────────────────────────────────
export default function AIDevOrchestrator({ onClose }) {
  const [files, setFiles] = useState(DEFAULT_FILES);
  const [activeFileId, setActiveFileId] = useState("main");
  const [terminalOutput, setTerminalOutput] = useState([
    { type: "system", text: "NexusVectis AI IDE — DevOps Orchestrator v2.0" },
    { type: "info", text: "Fleet AI ready. Type a prompt or run a preset." },
    { type: "success", text: "✓ Environment initialized" },
  ]);
  const [isRunning, setIsRunning] = useState(false);
  const [aiPrompt, setAiPrompt] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [activeStage, setActiveStage] = useState("code");
  const [stageStatus, setStageStatus] = useState({});
  const [activePanel, setActivePanel] = useState("editor"); // editor | terminal | pipeline | orchestrator
  const [bottomPanel, setBottomPanel] = useState("terminal"); // terminal | problems | output
  const [searchQuery, setSearchQuery] = useState("");
  const [showSearch, setShowSearch] = useState(false);
  const [orchestratorTasks, setOrchestratorTasks] = useState([
    { id: 1, name: "Fleet telemetry sync", status: "completed", agent: "DataAgent", duration: "1.2s" },
    { id: 2, name: "Anomaly detection run", status: "completed", agent: "AIAgent", duration: "3.4s" },
    { id: 3, name: "Route optimization", status: "running", agent: "RouteAgent", duration: "..." },
    { id: 4, name: "Report generation", status: "pending", agent: "ReportAgent", duration: "-" },
  ]);

  const activeFile = files.find(f => f.id === activeFileId);

  const log = (text, type = "default") => {
    setTerminalOutput(prev => [...prev, { text, type }]);
  };

  // ── Run current file ────────────────────────────────────────────────────────
  const runFile = async () => {
    if (isRunning || !activeFile) return;
    setIsRunning(true);
    setBottomPanel("terminal");
    log(`$ run ${activeFile.name}`, "system");
    log(`Executing ${activeFile.lang} code...`, "info");

    // Simulate pipeline stages
    for (const stage of PIPELINE_STAGES.slice(0, 3)) {
      setActiveStage(stage.id);
      setStageStatus(prev => ({ ...prev, [stage.id]: "running" }));
      await new Promise(r => setTimeout(r, 600));
      setStageStatus(prev => ({ ...prev, [stage.id]: "success" }));
    }

    // AI-powered execution simulation
    try {
      const result = await base44.integrations.Core.InvokeLLM({
        prompt: `You are a code execution engine. Simulate running this ${activeFile.lang} code and return realistic terminal output. The project is "NexusVectis" fleet management. Code:

${activeFile.content.slice(0, 800)}

Return a JSON with:
{
  "output": ["line1", "line2", ...],
  "exit_code": 0,
  "duration_ms": 1234,
  "summary": "short summary"
}`,
        response_json_schema: {
          type: "object",
          properties: {
            output: { type: "array", items: { type: "string" } },
            exit_code: { type: "number" },
            duration_ms: { type: "number" },
            summary: { type: "string" }
          }
        }
      });

      (result.output || ["Done"]).forEach(line => log(line, line.includes("Error") ? "error" : line.includes("✓") || line.includes("✅") ? "success" : "default"));
      log(`\nProcess exited with code ${result.exit_code ?? 0} in ${result.duration_ms ?? 800}ms`, result.exit_code === 0 ? "success" : "error");
    } catch {
      log("Process exited with code 0", "success");
    }

    setIsRunning(false);
  };

  // ── Deploy pipeline ─────────────────────────────────────────────────────────
  const runPipeline = async () => {
    if (isRunning) return;
    setIsRunning(true);
    setBottomPanel("terminal");
    setStageStatus({});
    log("$ nexusvectis deploy --env=production", "system");

    for (const stage of PIPELINE_STAGES) {
      setActiveStage(stage.id);
      setStageStatus(prev => ({ ...prev, [stage.id]: "running" }));
      log(`[${stage.label.toUpperCase()}] Starting...`, "info");
      await new Promise(r => setTimeout(r, 1000));

      const fail = stage.id === "scan" && Math.random() < 0.1;
      if (fail) {
        setStageStatus(prev => ({ ...prev, [stage.id]: "error" }));
        log(`[${stage.label.toUpperCase()}] ✗ Security vulnerability detected — CVE-2024-3822`, "error");
        log("Pipeline aborted. Fix vulnerabilities and retry.", "error");
        setIsRunning(false);
        return;
      }

      setStageStatus(prev => ({ ...prev, [stage.id]: "success" }));
      log(`[${stage.label.toUpperCase()}] ✓ Passed`, "success");
    }

    log("\n🚀 Deployment successful! Fleet AI v2.0 is live.", "success");
    log("Rollout: 100% • Health: ✓ • Latency: 12ms", "success");
    toast.success("Pipeline completed — Fleet AI deployed!");
    setIsRunning(false);
  };

  // ── AI Code Generation ──────────────────────────────────────────────────────
  const generateCode = async (prompt) => {
    if (!prompt.trim() || isGenerating) return;
    setIsGenerating(true);
    setBottomPanel("terminal");
    log(`$ ai generate: "${prompt}"`, "system");
    log("🤖 FLEET AI analyzing request...", "info");

    try {
      const result = await base44.integrations.Core.InvokeLLM({
        prompt: `You are an expert software engineer for "NexusVectis" — a fleet management & logistics AI platform.
The user wants to: "${prompt}"

Current file: ${activeFile?.name} (${activeFile?.lang})
Existing code context:
${activeFile?.content?.slice(0, 500) || ""}

Generate production-quality ${activeFile?.lang || "javascript"} code that:
1. Integrates with NexusVectis fleet data (vehicles, routes, shipments, alerts)
2. Follows DevOps best practices (error handling, logging, health checks)
3. Is modular and well-commented
4. Includes real-world patterns (retry logic, circuit breakers, observability)

Return JSON:
{
  "filename": "suggested_filename.ext",
  "language": "python|javascript|yaml|etc",
  "code": "full code here",
  "explanation": "what this does",
  "commands": ["pip install x", "npm run y"]
}`,
        response_json_schema: {
          type: "object",
          properties: {
            filename: { type: "string" },
            language: { type: "string" },
            code: { type: "string" },
            explanation: { type: "string" },
            commands: { type: "array", items: { type: "string" } }
          }
        },
        model: "claude_sonnet_4_6"
      });

      if (result.code) {
        const newFile = {
          id: `ai_${Date.now()}`,
          name: result.filename || `ai_generated.${result.language === "python" ? "py" : "js"}`,
          lang: LANG_MAP[result.filename?.split(".").pop()] || result.language || "javascript",
          content: result.code,
        };
        setFiles(prev => [...prev, newFile]);
        setActiveFileId(newFile.id);
        log(`✅ Generated: ${newFile.name}`, "success");
        log(`📋 ${result.explanation}`, "info");
        if (result.commands?.length) {
          log("Run these commands:", "warn");
          result.commands.forEach(cmd => log(`  $ ${cmd}`, "system"));
        }
        toast.success(`AI generated: ${newFile.name}`);
      }
    } catch (err) {
      log(`Error: ${err.message}`, "error");
    }

    setIsGenerating(false);
    setAiPrompt("");
  };

  // ── AI improve current file ─────────────────────────────────────────────────
  const improveFile = async (instruction) => {
    if (!activeFile || isGenerating) return;
    setIsGenerating(true);
    log(`$ ai improve: "${instruction}"`, "system");

    try {
      const result = await base44.integrations.Core.InvokeLLM({
        prompt: `Improve this ${activeFile.lang} code by applying: "${instruction}"

ORIGINAL CODE:
${activeFile.content}

Return ONLY the improved code as a raw string (no markdown, no explanation, just code):`,
        model: "claude_sonnet_4_6"
      });

      if (result && typeof result === "string" && result.length > 20) {
        setFiles(prev => prev.map(f => f.id === activeFileId ? { ...f, content: result.replace(/^```[\w]*\n?/, "").replace(/\n?```$/, "") } : f));
        log(`✅ Improvement applied: ${instruction}`, "success");
        toast.success("Code improved by AI");
      }
    } catch (err) {
      log(`Error: ${err.message}`, "error");
    }
    setIsGenerating(false);
  };

  // ── New file ────────────────────────────────────────────────────────────────
  const addNewFile = () => {
    const name = prompt("File name (e.g. app.py):") || "untitled.js";
    const ext = name.split(".").pop();
    const newFile = {
      id: `f_${Date.now()}`,
      name,
      lang: LANG_MAP[ext] || "javascript",
      content: `// ${name}\n// Created by FLEET AI IDE\n\n`,
    };
    setFiles(prev => [...prev, newFile]);
    setActiveFileId(newFile.id);
  };

  const deleteFile = (id) => {
    setFiles(prev => prev.filter(f => f.id !== id));
    if (activeFileId === id) setActiveFileId(files[0]?.id);
  };

  const copyCode = () => {
    if (activeFile) {
      navigator.clipboard.writeText(activeFile.content);
      toast.success("Code copied");
    }
  };

  const downloadFile = () => {
    if (!activeFile) return;
    const blob = new Blob([activeFile.content], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = activeFile.name;
    a.click();
  };

  const highlightedContent = useCallback((content) => {
    if (!content) return "";
    // Basic syntax highlighting via CSS classes — color keywords
    return content;
  }, []);

  const filteredContent = showSearch && searchQuery
    ? activeFile?.content?.split("\n").map((line, i) =>
        line.toLowerCase().includes(searchQuery.toLowerCase())
          ? `${String(i + 1).padStart(4, " ")}  ${line}`
          : null
      ).filter(Boolean).join("\n")
    : null;

  return (
    <div className="flex flex-col h-full bg-slate-950 text-white overflow-hidden">
      {/* ── Top toolbar ───────────────────────────────────────────── */}
      <div className="flex items-center gap-2 px-3 py-1.5 border-b border-slate-800 bg-slate-900 flex-shrink-0">
        <div className="flex items-center gap-2 mr-2">
          <Bot className="w-4 h-4 text-cyan-400" />
          <span className="text-xs font-bold text-cyan-400 tracking-widest uppercase font-mono">Fleet AI IDE</span>
        </div>

        {/* Panel toggles */}
        {[
          { id: "editor", label: "Editor", icon: Code2 },
          { id: "pipeline", label: "Pipeline", icon: GitBranch },
          { id: "orchestrator", label: "Orchestrator", icon: Layers },
        ].map(({ id, label, icon: Icon }) => (
          <button key={id}
            onClick={() => setActivePanel(id)}
            className={`flex items-center gap-1.5 px-2.5 py-1 rounded text-xs transition-all ${
              activePanel === id ? "bg-cyan-500/20 text-cyan-300 border border-cyan-500/40" : "text-slate-500 hover:text-slate-300"
            }`}>
            <Icon className="w-3 h-3" />
            {label}
          </button>
        ))}

        <div className="flex-1" />

        {/* Action buttons */}
        <button onClick={() => setShowSearch(!showSearch)} className="p-1.5 rounded text-slate-500 hover:text-slate-300 hover:bg-slate-800 transition-all">
          <Search className="w-3.5 h-3.5" />
        </button>
        <button onClick={copyCode} className="p-1.5 rounded text-slate-500 hover:text-slate-300 hover:bg-slate-800 transition-all">
          <Copy className="w-3.5 h-3.5" />
        </button>
        <button onClick={downloadFile} className="p-1.5 rounded text-slate-500 hover:text-slate-300 hover:bg-slate-800 transition-all">
          <Download className="w-3.5 h-3.5" />
        </button>
        <button onClick={runFile} disabled={isRunning}
          className={`flex items-center gap-1.5 px-3 py-1 rounded text-xs font-medium transition-all ${
            isRunning ? "bg-slate-700 text-slate-500" : "bg-green-600 hover:bg-green-500 text-white"
          }`}>
          {isRunning ? <Loader2 className="w-3 h-3 animate-spin" /> : <Play className="w-3 h-3" />}
          Run
        </button>
        <button onClick={runPipeline} disabled={isRunning}
          className={`flex items-center gap-1.5 px-3 py-1 rounded text-xs font-medium transition-all ${
            isRunning ? "bg-slate-700 text-slate-500" : "bg-violet-600 hover:bg-violet-500 text-white"
          }`}>
          <Cloud className="w-3 h-3" />
          Deploy
        </button>
      </div>

      {/* ── Pipeline stage bar ─────────────────────────────────────── */}
      {activePanel === "pipeline" && (
        <PipelineVisualizer activeStage={activeStage} stageStatus={stageStatus} />
      )}

      {/* ── Orchestrator panel ─────────────────────────────────────── */}
      {activePanel === "orchestrator" && (
        <div className="p-4 bg-slate-900 border-b border-slate-800 flex-shrink-0">
          <div className="flex items-center gap-2 mb-3">
            <Layers className="w-4 h-4 text-violet-400" />
            <p className="text-sm font-bold text-white">AI Agent Orchestrator</p>
            <div className="ml-auto flex items-center gap-1.5 text-xs text-green-400">
              <div className="w-1.5 h-1.5 rounded-full bg-green-400 animate-pulse" />
              3 agents active
            </div>
          </div>
          <div className="grid grid-cols-2 gap-2">
            {orchestratorTasks.map(task => (
              <div key={task.id} className={`flex items-center gap-2 p-2 rounded-lg border text-xs ${
                task.status === "completed" ? "border-green-500/30 bg-green-500/5" :
                task.status === "running" ? "border-amber-500/30 bg-amber-500/5" :
                "border-slate-700/50 bg-slate-800/30"
              }`}>
                <div className={`w-5 h-5 rounded flex items-center justify-center flex-shrink-0 ${
                  task.status === "completed" ? "bg-green-500/20" :
                  task.status === "running" ? "bg-amber-500/20" : "bg-slate-700"
                }`}>
                  {task.status === "completed" ? <Check className="w-3 h-3 text-green-400" /> :
                   task.status === "running" ? <Loader2 className="w-3 h-3 text-amber-400 animate-spin" /> :
                   <ChevronRight className="w-3 h-3 text-slate-500" />}
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-slate-200 truncate">{task.name}</p>
                  <p className="text-slate-500 text-[10px]">{task.agent} · {task.duration}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ── Search bar ────────────────────────────────────────────── */}
      {showSearch && (
        <div className="flex items-center gap-2 px-3 py-2 bg-slate-900 border-b border-slate-800">
          <Search className="w-3.5 h-3.5 text-slate-500" />
          <input
            autoFocus
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
            placeholder="Search in file..."
            className="flex-1 bg-transparent text-sm text-white placeholder-slate-600 outline-none font-mono"
          />
          {searchQuery && <span className="text-xs text-slate-500">{activeFile?.content?.split("\n").filter(l => l.toLowerCase().includes(searchQuery.toLowerCase())).length} matches</span>}
        </div>
      )}

      {/* ── Main area ─────────────────────────────────────────────── */}
      <div className="flex flex-1 min-h-0">
        {/* File explorer */}
        <FileExplorer
          files={files}
          activeFileId={activeFileId}
          onSelect={setActiveFileId}
          onNew={addNewFile}
          onDelete={deleteFile}
        />

        {/* Editor + bottom panel */}
        <div className="flex flex-col flex-1 min-w-0">
          {/* Editor tabs */}
          <div className="flex items-center gap-0 border-b border-slate-800 bg-slate-900 overflow-x-auto flex-shrink-0">
            {files.map(f => (
              <button key={f.id}
                onClick={() => setActiveFileId(f.id)}
                className={`flex items-center gap-1.5 px-3 py-1.5 text-[11px] font-mono border-r border-slate-800 whitespace-nowrap transition-colors ${
                  f.id === activeFileId ? "bg-slate-950 text-cyan-300 border-b-2 border-b-cyan-500" : "text-slate-500 hover:text-slate-300 hover:bg-slate-800"
                }`}>
                <div className="w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: LANG_COLORS[f.lang] || "#94a3b8" }} />
                {f.name}
              </button>
            ))}
          </div>

          {/* Code editor */}
          <div className="flex-1 overflow-hidden relative" style={{ minHeight: 0 }}>
            <div className="absolute inset-0 overflow-auto">
              <div className="flex">
                {/* Line numbers */}
                <div className="select-none py-3 pr-3 pl-3 text-right text-slate-700 text-xs font-mono leading-5 border-r border-slate-800 bg-slate-950 min-w-[48px] flex-shrink-0">
                  {(filteredContent || activeFile?.content || "").split("\n").map((_, i) => (
                    <div key={i}>{i + 1}</div>
                  ))}
                </div>
                {/* Code textarea */}
                <textarea
                  value={filteredContent || activeFile?.content || ""}
                  onChange={e => {
                    if (!filteredContent) {
                      setFiles(prev => prev.map(f => f.id === activeFileId ? { ...f, content: e.target.value } : f));
                    }
                  }}
                  readOnly={!!filteredContent}
                  className="flex-1 py-3 px-4 bg-slate-950 text-slate-200 font-mono text-xs leading-5 resize-none outline-none border-none min-w-0"
                  spellCheck={false}
                  style={{ minHeight: "100%", tabSize: 2 }}
                />
              </div>
            </div>
          </div>

          {/* AI Prompt bar */}
          <div className="flex items-center gap-2 px-3 py-2 border-t border-slate-800 bg-slate-900 flex-shrink-0">
            <Bot className="w-4 h-4 text-violet-400 flex-shrink-0" />
            <input
              value={aiPrompt}
              onChange={e => setAiPrompt(e.target.value)}
              onKeyDown={e => {
                if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); generateCode(aiPrompt); }
              }}
              placeholder="AI: Generate code, refactor, add tests, create Dockerfile..."
              className="flex-1 bg-transparent text-sm text-white placeholder-slate-600 outline-none"
            />
            <div className="flex items-center gap-1 flex-shrink-0">
              {AI_PRESETS.slice(0, 3).map(p => (
                <button key={p.label}
                  onClick={() => improveFile(p.label)}
                  disabled={isGenerating}
                  className="px-2 py-1 rounded text-[10px] text-slate-500 hover:text-slate-300 hover:bg-slate-800 transition-all border border-slate-800 hover:border-slate-600">
                  {p.icon}
                </button>
              ))}
              <button
                onClick={() => generateCode(aiPrompt)}
                disabled={isGenerating || !aiPrompt.trim()}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded text-xs font-medium transition-all ${
                  isGenerating || !aiPrompt.trim()
                    ? "bg-slate-800 text-slate-600"
                    : "bg-violet-600 hover:bg-violet-500 text-white"
                }`}>
                {isGenerating ? <Loader2 className="w-3 h-3 animate-spin" /> : <Zap className="w-3 h-3" />}
                Generate
              </button>
            </div>
          </div>

          {/* AI preset quick actions */}
          <div className="flex items-center gap-1 px-3 py-1.5 border-t border-slate-800/50 bg-slate-900/50 overflow-x-auto flex-shrink-0">
            {AI_PRESETS.map(p => (
              <button key={p.label}
                onClick={() => improveFile(p.label)}
                disabled={isGenerating}
                className="flex items-center gap-1 px-2 py-0.5 rounded text-[10px] text-slate-500 hover:text-slate-200 hover:bg-slate-700 transition-all whitespace-nowrap border border-transparent hover:border-slate-600">
                <span>{p.icon}</span>
                <span>{p.label}</span>
              </button>
            ))}
          </div>

          {/* Bottom panel tabs */}
          <div className="flex items-center gap-1 px-3 border-t border-slate-800 bg-slate-900 flex-shrink-0">
            {["terminal", "problems", "output"].map(tab => (
              <button key={tab}
                onClick={() => setBottomPanel(tab)}
                className={`px-3 py-1.5 text-[10px] uppercase tracking-widest font-bold transition-colors ${
                  bottomPanel === tab ? "text-cyan-400 border-b-2 border-cyan-500" : "text-slate-600 hover:text-slate-400"
                }`}>
                {tab}
              </button>
            ))}
            <div className="flex-1" />
            <span className="text-[10px] text-slate-600 font-mono">
              {activeFile?.lang} · {activeFile?.content?.split("\n").length || 0} lines · UTF-8
            </span>
          </div>

          {/* Bottom panel content */}
          <div className="flex-shrink-0" style={{ height: 160 }}>
            {bottomPanel === "terminal" && (
              <TerminalEmulator
                output={terminalOutput}
                isRunning={isRunning}
                onClear={() => setTerminalOutput([])}
              />
            )}
            {bottomPanel === "problems" && (
              <div className="h-full bg-slate-950 p-3 font-mono text-xs text-slate-500 flex items-center justify-center">
                <div className="flex items-center gap-2 text-green-400">
                  <Check className="w-4 h-4" />
                  No problems detected
                </div>
              </div>
            )}
            {bottomPanel === "output" && (
              <div className="h-full bg-slate-950 p-3 font-mono text-xs overflow-auto">
                <p className="text-slate-600">[AI IDE] Output ready</p>
                <p className="text-cyan-400">Fleet AI Orchestrator v2.0 initialized</p>
                <p className="text-slate-500">Organization: NexusVectis</p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}